apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: samordning-hendelse-api
  namespace: default
  labels:
    team: teampeon
spec:
  image: repo.adeo.no:5443/samordning-hendelse-api:latest
  port: 8080
  team: teampeon
  liveness:
    path: isAlive
  readiness:
    path: isReady
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/samordning-hendelse-api/deafult
        mountPath: /var/run/secrets/nais.io/vault
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
