apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: samordning-hendelse-api
  namespace: {{namespace}}
  labels:
    team: teampeon
spec:
  image: repo.adeo.no:5443/samordning-hendelse-api:{{version}}
  port: 8080
  team: teampeon
  ingresses:
    - {{ingress}}
  liveness:
    path: isAlive
  readiness:
    path: isReady
  vault:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus