apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: samordning-hendelse-api
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{image}}
  port: 8080
  team: {{team}}
  ingresses:
    - {{ingress}}
  webproxy: true
  maskinporten:
    enabled: true
  liveness:
    path: actuator/health/liveness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: actuator/health/readiness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  vault:
    enabled: true
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{profile}}
