apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: samordning-hendelse-api
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{image}}
  port: 8080
  team: {{team}}
  ingresses:
    - {{ingress}}
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  vault:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "v1/samordning"
          product: "pensjon"
          enabled: true
          delegatable: {{delegatable}}
          delegation: sam-api-delegation-scheme
          consumers:
            - name: SPK
              orgno: 982583462
            - name: OSLO PENSJONSFORSIKRING AS
              orgno: 982759412
            - name: KLP
              orgno: 938708606
            - name: GABLER PENSJONSTJENESTER AS
              orgno: 916833520
            - name: Storebrand Pensjonstjenester AS
              orgno: 931936492
            - name: Storebrand Livsforsikring AS
              orgno: 958995369
            - name: Viken
              orgnr: 974358603
            - name: NAV
              orgno: 889640782
    delegations:
      - name: sam-api-delegation-scheme
        enabled: true
        title:
          - code: nb_NO
            value: pensjon/samordning API for samarbeidspartner
          - code: nn_NO
            value: pensjon/samordning API for samarbeidspartnarar
          - code: en
            value: pensjon/samordning API for partners
        description:
          - code: nb_NO
            value: Gir samarbeidspartnere tilgang til pensjon/samordning.
          - code: nn_NO
            value: Gir samarbeidspartnarar tilgang på pensjon/samordning.
          - code: en
            value: Gives partners access to pensjon/samordning.
        defaultlanguage: nb_NO
        authlevel: 2
  webproxy: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{spring_profiles_active}}
  prometheus:
    enabled: true
    path: actuator/prometheus
