apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: samordning-hendelse-api-q2
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://samordning-hendelse-api-q2.intern.dev.nav.no
    - https://samordning-hendelse-api-q2.dev-fss-pub.nais.io
  webproxy: true
  maskinporten:
    enabled: true
  liveness:
    path: actuator/health/liveness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: actuator/health/readiness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  vault:
    enabled: true
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  env:
    - name: BOOTSTRAP_APPNAME
      value: samordning-hendelse-api-q2/pensjonsamhandling
    - name: SPRING_PROFILES_ACTIVE
      value: dev,q2
    - name: LOGGING_CONFIG
      value: classpath:logback-json.xml
    - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
      value: "https://elastic-apm.adeo.no"
    - name: "OTEL_METRICS_EXPORTER"
      value: "otlp"
    - name: "OTEL_LOGS_EXPORTER"
      value: "otlp"
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "service.name=samordning-hendelse-api,deployment.environment=q2"
    - name: "OTEL_TRACES_EXPORTER"
      value: "otlp"
  kafka:
    pool: nav-dev