apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: samordning-hendelser-q1
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  krakend: pensjon-samordning-q1
  auth:
    name: maskinporten
    cache: true
    scopes:
      - nav:pensjon/v1/samordning
  rateLimit:
    maxRate: 100
    every: 60s
  endpoints:
    - path: /samordning/hendelser
      method: GET
      timeout: 60s
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
      queryParams:
        - tpnr
        - side
        - antall
        - sekvensnummer
      backendHost: https://samordning-hendelse-api-q1.dev-fss-pub.nais.io
      backendPath: /hendelser
---
apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: samordning-hendelser-ytelser-q1
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  krakend: pensjon-samordning-q1
  auth:
    name: maskinporten
    cache: true
    scopes:
      - nav:pensjon/v1/samordning
  rateLimit:
    maxRate: 100
    every: 60s
  endpoints:
    - path: /samordning/hendelser/ytelser
      method: GET
      timeout: 60s
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
      queryParams:
        - tpnr
        - ytelse
        - side
        - antall
        - sekvensnummer
      backendHost: https://samordning-hendelse-api-q1.dev-fss-pub.nais.io
      backendPath: /hendelser/ytelser