apiVersion: krakend.nais.io/v1
kind: Krakend
metadata:
  name: pensjon-samordning-q1
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  authProviders:
    - name: maskinporten
      alg: RS256
      jwkUrl: "https://test.maskinporten.no/jwk"
      issuer: "https://test.maskinporten.no/"
  ingress:
    className: nais-ingress-external
    enabled: true
    hosts:
      - host: pensjon-q1-gw.ekstern.dev.nav.no
        paths:
          - path: /samordning/
            pathType: ImplementationSpecific