logging.level:
  no.nav.pensjonsamhandling.maskinporten.validation: INFO
  no.nav.samordning.hendelser: INFO

TPCONFIG_URL: https://tp.nais.adeo.no/api/tpconfig

maskinporten.validation.baseUrl: https://maskinporten.no/
