tpconfig.url: https://tp-q1.dev.intern.nav.no/api/tpconfig

maskinporten.validation:
  environment: DEV
  permit-all: 889640782
  required: 940415683

MAX_POOL_SIZE: 50

VEDTAK_HENDELSE_KAFKA_TOPIC: pensjonsamhandling.sam-vedtak-hendelser-q1
YTELSE_HENDELSE_KAFKA_TOPIC: pensjonsamhandling.tp-hendelser-q1
