tpconfig.url: https://tp.nais.adeo.no/api/tpconfig

oauth2:
  maskinporten:
    issuer: https://maskinporten.no/
    jwkSetUri: https://maskinporten.no/jwk
  sts:
    issuer: https://security-token-service.nais.adeo.no
    jwkSetUri: https://security-token-service.nais.adeo.no/rest/v1/sts/jwks
