tpconfig.url: https://tp-q2.dev.intern.nav.no/api/tpconfig

oauth2:
  acceptAll: 889640782
  maskinporten:
    issuer: https://test.maskinporten.no/
    jwkSetUri: https://test.maskinporten.no/jwk
  maskinportenOld:
    issuer: https://ver2.maskinporten.no/
    jwkSetUri: https://ver2.maskinporten.no/jwk
  sts:
    issuer: https://security-token-service.nais.preprod.local
    jwkSetUri: https://security-token-service.dev.adeo.no/rest/v1/sts/jwks

MAX_POOL_SIZE: 3

VEDTAK_HENDELSE_KAFKA_TOPIC: pensjonsamhandling.sam-vedtak-hendelser-q2
YTELSE_HENDELSE_KAFKA_TOPIC: pensjonsamhandling.tp-hendelser-q2

spring:
  jpa:
    hibernate:
      ddl-auto: update