apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: samordning-hendelse-api
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://samordning-hendelse-api.nais.preprod.local
    - https://samordning-hendelse-api.dev.intern.nav.no
    - https://samordning-hendelse-api-q1.dev-fss-pub.nais.io
  webproxy: true
  maskinporten:
    enabled: true
  liveness:
    path: actuator/health/liveness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: actuator/health/readiness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  startup:
    path: actuator/health/readiness
    initialDelay: 45
    failureThreshold: 60
    periodSeconds: 5
  envFrom:
    - secret: samordning-hendelse-api
  vault:
    enabled: true
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  env:
    - name: BOOTSTRAP_APPNAME
      value: samordning-hendelse-api/pensjonsamhandling
    - name: SPRING_PROFILES_ACTIVE
      value: q1
    - name: LOGGING_CONFIG
      value: classpath:logback-json.xml
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "deployment.environment.name=q1"
  kafka:
    pool: nav-dev
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: grafana-lgtm
        - id: elastic-apm
    logging:
      destinations:
        - id: loki
