apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: samordning-hendelse-api
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://samordning-hendelse-api.nav.no
  maskinporten:
    enabled: true
  liveness:
    path: actuator/health/liveness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: actuator/health/readiness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  startup:
    path: actuator/health/readiness
    initialDelay: 45
    failureThreshold: 60
    periodSeconds: 5
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        tier: db-custom-1-3840
        highAvailability: true
        diskSize: 5
        diskAutoresize: true
        pointInTimeRecovery: true
        databases:
          - name: samordning-hendelser
        flags:
          - name: cloudsql.enable_pgaudit
            value: "on"
          - name: pgaudit.log_parameter
            value: "on"
          - name: pgaudit.log
            value: "write,ddl,role,read"
  accessPolicy:
    outbound:
      external:
        - host: tp.prod-fss-pub.nais.io
  replicas:
    min: 0
    max: 0
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: LOGGING_CONFIG
      value: classpath:logback-json.xml
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment.name=p"
  kafka:
    pool: nav-prod
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
