CREATE OR REPLACE FUNCTION SET_SEKVENSNUMMER_FOR_TPNR()
    RETURNS TRIGGER AS $$
DECLARE
    NEXT_SEKVENSNUMMER BIGINT;
BEGIN
    EXECUTE format(
            'SELECT COALESCE(MAX(SEKVENSNUMMER), 0) + 1 FROM %I.%I WHERE TPNR = $1',
            TG_TABLE_SCHEMA,
            TG_TABLE_NAME
            )
        INTO NEXT_SEKVENSNUMMER
        USING NEW.TPNR;

    NEW.SEKVENSNUMMER := NEXT_SEKVENSNUMMER;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql
@@

CREATE OR REPLACE FUNCTION SET_SEKVENSNUMMER_FOR_MOTTAKER()
    RETURNS TRIGGER AS $$
DECLARE
    NEXT_SEKVENSNUMMER BIGINT;
BEGIN
    EXECUTE format(
            'SELECT COALESCE(MAX(SEKVENSNUMMER), 0) + 1 FROM %I.%I WHERE MOTTAKER = $1',
            TG_TABLE_SCHEMA,
            TG_TABLE_NAME
            )
        INTO NEXT_SEKVENSNUMMER
        USING NEW.MOTTAKER;

    NEW.SEKVENSNUMMER := NEXT_SEKVENSNUMMER;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql
@@

CREATE TABLE IF NOT EXISTS VEDTAK_HENDELSE
(
    ID                  SERIAL PRIMARY KEY,
    SEKVENSNUMMER       BIGINT NOT NULL DEFAULT 0,
    TPNR                VARCHAR(20),
    YTELSES_TYPE        VARCHAR(20) NOT NULL,
    IDENTIFIKATOR       VARCHAR(20) NOT NULL,
    VEDTAK_ID           VARCHAR(20) NOT NULL,
    SAM_ID              VARCHAR(20),
    FOM                 DATE NOT NULL,
    TOM                 DATE
)
@@

CREATE TRIGGER VEDTAK_HENDELSE_SEKVENSNUMMER_TRIGGER
    BEFORE INSERT ON VEDTAK_HENDELSE
    FOR EACH ROW
EXECUTE PROCEDURE SET_SEKVENSNUMMER_FOR_TPNR()
@@

CREATE TABLE IF NOT EXISTS YTELSE_HENDELSER
(
    ID                  BIGSERIAL PRIMARY KEY,
    SEKVENSNUMMER       BIGINT NOT NULL DEFAULT 0,
    TPNR                VARCHAR(20) not null,
    MOTTAKER            VARCHAR(20) not null,
    IDENTIFIKATOR       VARCHAR(20) not null,
    HENDELSE_TYPE       VARCHAR(20) not null,
    YTELSE_TYPE         VARCHAR(20) not null,
    DATO_BRUK_FOM       TIMESTAMP   not null,
    DATO_BRUK_TOM       TIMESTAMP
)
@@

CREATE TRIGGER YTELSE_HENDELSER_SEKVENSNUMMER_TRIGGER
    BEFORE INSERT ON YTELSE_HENDELSER
    FOR EACH ROW
EXECUTE PROCEDURE SET_SEKVENSNUMMER_FOR_MOTTAKER()
@@

CREATE TABLE IF NOT EXISTS PERSON_ENDRING
(
    ID                  BIGSERIAL PRIMARY KEY,
    SEKVENSNUMMER       BIGINT NOT NULL DEFAULT 0,
    TPNR                VARCHAR(20) not null,
    FNR                 VARCHAR(20) not null,
    FNR_GAMMELT         VARCHAR(20),
    SIVILSTAND          VARCHAR(20),
    SIVILSTAND_DATO     DATE,
    DOEDSDATO           DATE,
    ADRESSE             JSON,
    MELDINGSKODE        VARCHAR(20) not null
)
@@

CREATE TRIGGER PERSON_ENDRING_SEKVENSNUMMER_TRIGGER
    BEFORE INSERT ON PERSON_ENDRING
    FOR EACH ROW
EXECUTE PROCEDURE SET_SEKVENSNUMMER_FOR_TPNR()
@@


CREATE TABLE IF NOT EXISTS PERSON_HENDELSE
(
    HENDELSE_ID            CHAR(36) NOT NULL,
    MELDINGSKODE           VARCHAR(20) NOT NULL,
    OPPRETTET_TIDSPUNKT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PERSON_HENDELSE_PK PRIMARY KEY (HENDELSE_ID, MELDINGSKODE)
)
@@

CREATE TABLE IF NOT EXISTS MANGLENDE_REFUSJONSKRAV
(
    ID                  BIGSERIAL PRIMARY KEY,
    SEKVENSNUMMER       BIGINT NOT NULL DEFAULT 0,
    TPNR                VARCHAR(20) not null,
    FNR                 VARCHAR(20) not null,
    SAM_ID              VARCHAR(20) not null,
    SVARFRIST           DATE not null
)
@@

CREATE TRIGGER MANGLENDE_REFUSJONKRAV_SEKVENSNUMMER_TRIGGER
    BEFORE INSERT ON MANGLENDE_REFUSJONSKRAV
    FOR EACH ROW
EXECUTE PROCEDURE SET_SEKVENSNUMMER_FOR_TPNR()
@@
