apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: samordning-hendelser-q2
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  krakend: pensjon-samordning-q2
  auth:
    name: maskinporten
    cache: true
    scopes:
      - nav:pensjon/v1/samordning
  rateLimit:
    maxRate: 100
    clientMaxRate: 200
    every: 60s
  endpoints:
    - path: /samordning/hendelser
      method: GET
      timeout: 60s
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
      queryParams:
        - tpnr
        - side
        - antall
        - sekvensnummer
      backendHost: https://samordning-hendelse-api-q2.dev-fss-pub.nais.io
      backendPath: /hendelser
---
apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: samordning-hendelser-vedtak-q2
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  krakend: pensjon-samordning-q2
  auth:
    name: maskinporten
    cache: true
    scopes:
      - nav:pensjon/v1/samordning
  rateLimit:
    maxRate: 100
    clientMaxRate: 200
    every: 60s
  endpoints:
    - path: /samordning/hendelser/vedtak
      method: GET
      timeout: 60s
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
      queryParams:
        - tpnr
        - side
        - antall
        - sekvensnummer
      backendHost: https://samordning-hendelse-api-q2.dev-fss-pub.nais.io
      backendPath: /hendelser/vedtak
---
apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: samordning-hendelser-ytelser-q2
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  krakend: pensjon-samordning-q2
  auth:
    name: maskinporten
    cache: true
    scopes:
      - nav:pensjon/v1/samordning
  rateLimit:
    maxRate: 100
    clientMaxRate: 200
    every: 60s
  endpoints:
    - path: /samordning/hendelser/ytelser
      method: GET
      timeout: 60s
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
      queryParams:
        - tpnr
        - side
        - antall
        - sekvensnummer
      backendHost: https://samordning-hendelse-api-q2.dev-fss-pub.nais.io
      backendPath: /hendelser/ytelser
---
apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: samordning-hendelser-personer-q2
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  krakend: pensjon-samordning-q2
  auth:
    name: maskinporten
    cache: true
    scopes:
      - nav:pensjon/v1/samordning
  rateLimit:
    maxRate: 100
    clientMaxRate: 200
    every: 60s
  endpoints:
    - path: /samordning/hendelser/personer
      method: GET
      timeout: 60s
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
      queryParams:
        - tpnr
        - side
        - antall
        - sekvensnummer
      backendHost: https://samordning-hendelse-api-q2.dev-fss-pub.nais.io
      backendPath: /hendelser/personer
---
apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: samordning-hendelser-manglendeRefusjonskrav-q2
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  krakend: pensjon-samordning-q2
  auth:
    name: maskinporten
    cache: true
    scopes:
      - nav:pensjon/v1/samordning
  rateLimit:
    maxRate: 100
    every: 60s
  endpoints:
    - path: /samordning/hendelser/manglendeRefusjonskrav
      method: GET
      timeout: 60s
      forwardHeaders:
        - Authorization
        - Content-Type
        - X-Request-Id
      queryParams:
        - tpnr
        - side
        - antall
        - sekvensnummer
      backendHost: https://samordning-hendelse-api-q2.dev-fss-pub.nais.io
      backendPath: /hendelser/manglendeRefusjonskrav