apiVersion: krakend.nais.io/v1
kind: Krakend
metadata:
  name: pensjon-samordning
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  authProviders:
    - name: maskinporten
      alg: RS256
      jwkUrl: "https://maskinporten.no/jwk"
      issuer: "https://maskinporten.no/"
  ingress:
    className: nais-ingress-external
    enabled: true
    hosts:
      - host: pensjon-gw.nav.no
        paths:
          - path: /samordning/
            pathType: ImplementationSpecific