CREATE TABLE IF NOT EXISTS YTELSE_HENDELSER
(
    ID                  BIGSERIAL PRIMARY KEY,
    SEKVENSNUMMER       BIGSERIAL NOT NULL,
    TPNR                VARCHAR(20) NOT NULL,
    MOTTAKER            VARCHAR(20) NOT NULL,
    IDENTIFIKATOR       VARCHAR(20) NOT NULL,
    HENDELSE_TYPE       VARCHAR(20) NOT NULL,
    YTELSE_TYPE         VARCHAR(20) NOT NULL,
    DATO_BRUK_FOM       TIMESTAMP NOT NULL,
    DATO_BRUK_TOM       TIMESTAMP
);
