CREATE TABLE IF NOT EXISTS PERSON_ENDRING
(
    ID                  BIGSERIAL PRIMARY KEY,
    SEKVENSNUMMER       BIGSERIAL NOT NULL,
    TPNR                VARCHAR(20) NOT NULL,
    FNR                 VARCHAR(20) NOT NULL,
    FNR_GAMMELT         VARCHAR(20),
    SIVILSTAND          VARCHAR(20),
    SIVILSTAND_DATO     DATE,
    DOEDSDATO           DATE,
    MELDINGSKODE        VARCHAR(20) NOT NULL
);
