CREATE TABLE IF NOT EXISTS PERSON_HENDELSE
(
    HENDELSE_ID            CHAR(36) NOT NULL,
    MELDINGSKODE           VARCHAR(20) NOT NULL,
    OPPRETTET_TIDSPUNKT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PERSON_HENDELSE_PK PRIMARY KEY (HENDELSE_ID, MELDINGSKODE)
);
