CREATE TABLE IF NOT EXISTS MANGLENDE_REFUSJONSKRAV
(
    ID                  BIGSERIAL PRIMARY KEY,
    SEKVENSNUMMER       BIGSERIAL NOT NULL,
    TPNR                VARCHAR(20) NOT NULL,
    FNR                 VARCHAR(20) NOT NULL,
    SAM_ID              VARCHAR(20) NOT NULL,
    SVARFRIST           DATE NOT NULL
);
