CREATE OR REPLACE FUNCTION SET_SEKVENSNUMMER_FOR_TPNR()
    RETURNS TRIGGER AS $$
DECLARE
    NEXT_SEKVENSNUMMER BIGINT;
BEGIN
    EXECUTE format(
            'SELECT COALESCE(MAX(SEKVENSNUMMER), 0) + 1 FROM %I.%I WHERE TPNR = $1',
            TG_TABLE_SCHEMA,
            TG_TABLE_NAME
            )
        INTO NEXT_SEKVENSNUMMER
        USING NEW.TPNR;

    NEW.SEKVENSNUMMER := NEXT_SEKVENSNUMMER;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SET_SEKVENSNUMMER_FOR_MOTTAKER()
    RETURNS TRIGGER AS $$
DECLARE
    NEXT_SEKVENSNUMMER BIGINT;
BEGIN
    EXECUTE format(
            'SELECT COALESCE(MAX(SEKVENSNUMMER), 0) + 1 FROM %I.%I WHERE MOTTAKER = $1',
            TG_TABLE_SCHEMA,
            TG_TABLE_NAME
            )
        INTO NEXT_SEKVENSNUMMER
        USING NEW.MOTTAKER;

    NEW.SEKVENSNUMMER := NEXT_SEKVENSNUMMER;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

ALTER TABLE HENDELSER
    ADD SEKVENSNUMMER BIGINT NOT NULL DEFAULT 0,
    ADD YTELSES_TYPE VARCHAR(32) NOT NULL DEFAULT '',
    ADD IDENTIFIKATOR VARCHAR(20) NOT NULL DEFAULT '',
    ADD VEDTAK_ID VARCHAR(20) NOT NULL DEFAULT '',
    ADD SAM_ID VARCHAR(20),
    ADD FOM DATE NOT NULL DEFAULT '2001-01-01',
    ADD TOM DATE;

UPDATE HENDELSER SET
    SEKVENSNUMMER = row_number() OVER (PARTITION BY TPNR ORDER BY ID),
    YTELSES_TYPE = HENDELSE_DATA -> 'ytelsesType',
    IDENTIFIKATOR = HENDELSE_DATA -> 'identifikator',
    VEDTAK_ID = HENDELSE_DATA -> 'vedtakId',
    SAM_ID = HENDELSE_DATA -> 'samId',
    FOM = HENDELSE_DATA -> 'fom',
    TOM = HENDELSE_DATA -> 'tom'
    WHERE YTELSES_TYPE = '';

ALTER TABLE HENDELSER
    DROP COLUMN HENDELSE_DATA,
    ALTER COLUMN YTELSES_TYPE DROP DEFAULT,
    ALTER COLUMN IDENTIFIKATOR DROP DEFAULT,
    ALTER COLUMN VEDTAK_ID DROP DEFAULT,
    ALTER COLUMN FOM DROP DEFAULT;
ALTER TABLE HENDELSER RENAME TO VEDTAK_HENDELSE;
CREATE TRIGGER VEDTAK_HENDELSE_SEKVENSNUMMER_TRIGGER
    BEFORE INSERT ON VEDTAK_HENDELSE
    FOR EACH ROW
    EXECUTE PROCEDURE SET_SEKVENSNUMMER_FOR_TPNR();

ALTER TABLE YTELSE_HENDELSER
    ALTER COLUMN SEKVENSNUMMER TYPE BIGINT,
    ALTER COLUMN SEKVENSNUMMER SET NOT NULL,
    ALTER COLUMN SEKVENSNUMMER SET DEFAULT 0;
CREATE TRIGGER YTELSE_HENDELSER_SEKVENSNUMMER_TRIGGER
    BEFORE INSERT ON YTELSE_HENDELSER
    FOR EACH ROW
    EXECUTE PROCEDURE SET_SEKVENSNUMMER_FOR_MOTTAKER();

ALTER TABLE MANGLENDE_REFUSJONSKRAV
    ALTER COLUMN SEKVENSNUMMER TYPE BIGINT,
    ALTER COLUMN SEKVENSNUMMER SET NOT NULL,
    ALTER COLUMN SEKVENSNUMMER SET DEFAULT 0;
CREATE TRIGGER MANGLENDE_REFUSJONSKRAV_SEKVENSNUMMER_TRIGGER
    BEFORE INSERT ON MANGLENDE_REFUSJONSKRAV
    FOR EACH ROW
    EXECUTE PROCEDURE SET_SEKVENSNUMMER_FOR_TPNR();

ALTER TABLE PERSON_ENDRING
    ALTER COLUMN SEKVENSNUMMER TYPE BIGINT,
    ALTER COLUMN SEKVENSNUMMER SET NOT NULL,
    ALTER COLUMN SEKVENSNUMMER SET DEFAULT 0;
CREATE TRIGGER PERSON_ENDRING_SEKVENSNUMMER_TRIGGER
    BEFORE INSERT ON PERSON_ENDRING
    FOR EACH ROW
    EXECUTE PROCEDURE SET_SEKVENSNUMMER_FOR_TPNR();
