name: Auto-merge Dependabot Patch Updates

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check for dependencies label
        id: label_check
        run: |
          if echo "${{ join(github.event.pull_request.labels.*.name, ' ') }}" | grep -w "dependencies"; then
            echo "has_dependencies_label=true" >> $GITHUB_OUTPUT
          else
            echo "has_dependencies_label=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if PR is a patch update
        id: check
        run: |
          title="${{ github.event.pull_request.title }}"
          echo "PR Title: $title"
          # Match title like: Bump xxx from x.y.z to x.y.w (same x and y, z != w)
          if [[ "$title" =~ ^(B|b)ump\ .*\ from\ ([0-9]+)\.([0-9]+)\.([0-9]+)\ to\ ([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          from_major=${BASH_REMATCH[2]}
          from_minor=${BASH_REMATCH[3]}
          from_patch=${BASH_REMATCH[4]}
          to_major=${BASH_REMATCH[5]}
          to_minor=${BASH_REMATCH[6]}
          to_patch=${BASH_REMATCH[7]}

            echo "Parsed version bump:"
            echo "  From: $from_major.$from_minor.$from_patch"
            echo "  To:   $to_major.$to_minor.$to_patch"
          
            if [[ "$from_major" == "$to_major" && "$from_minor" == "$to_minor" && "$from_patch" != "$to_patch" ]]; then
              echo "patch_update=true" >> $GITHUB_OUTPUT
            else
              echo "patch_update=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No match for patch update regex"
            echo "patch_update=false" >> $GITHUB_OUTPUT
          fi

      - name: Debug PR Info
        run: gh pr view "$PR_NUMBER" --json state,number,title,author,mergeable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Enable auto-merge
        if: steps.check.outputs.patch_update == 'true' && steps.label_check.outputs.has_dependencies_label == 'true'
        run: gh pr merge "$PR_NUMBER" --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Failed auto-merge
        if: steps.check.outputs.patch_update == 'false' || steps.label_check.outputs.has_dependencies_label == 'false'
        run: exit 1