name: Deploy to Q1

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Which version to deploy (e.g. 2020.01.01-12.55-a1b2c3d4e5f6)"
        required: true

jobs:
  dev_deploy:
    name: Deploy to Dev
    permissions:
      contents: "read"
      id-token: "write"  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Input
        run: echo "version = ${{ github.event.inputs.version }}"
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/nais-q1.yaml
          IMAGE: "docker.pkg.github.com/${{ github.repository }}/samordning-hendelse-api:${{ github.event.inputs.version }}"
          TEAM: pensjonsamhandling

      - name: Deploy krakenD config
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/apiendpoints/krakend-q1.yaml

      - name: Deploy apiEndpoints config
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/apiendpoints/apiendpoints-q1.yaml

