name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Which version to deploy (e.g. 2020.01.01-12.55-a1b2c3d4e5f6)"
        required: true

jobs:
  prod_deploy:
    name: Deploy to Prod
    permissions:
      contents: "read"
      id-token: "write"  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Input
        run: echo "version = ${{ github.event.inputs.version }}"
      - name: Deploy to prod-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: .nais/nais-prod.yaml
          IMAGE: "docker.pkg.github.com/${{ github.repository }}/samordning-hendelse-api:${{ github.event.inputs.version }}"
          TEAM: pensjonsamhandling

