name: "Deploy to dev"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Which version to deploy (e.g. 2020.01.01-12.55-a1b2c3d4e5f6)"
        required: true
      q1:
        description: 'Q1'
        required: true
        default: true
        type: boolean
      q2:
        description: 'Q2'
        required: true
        default: true
        type: boolean


jobs:
  deployAppToQ1:
    name: Deploy to Dev
    if: inputs.q1
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4
      - name: Input
        run: echo "version = ${{ inputs.version }}"
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/nais-q1.yaml
          IMAGE: ghcr.io/${{ github.repository }}/samordning-hendelse-api:${{ inputs.version }}
          TEAM: pensjonsamhandling
      - name: Deploy krakenD config
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/apiendpoints/krakend-q1.yaml
      - name: Deploy apiEndpoints config
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/apiendpoints/apiendpoints-q1.yaml


  deployAppToQ2:
    name: Deploy to Q2
    if: inputs.q2
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4
      - name: Input
        run: echo "version = ${{ inputs.version }}"
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/nais-q2.yaml
          IMAGE: ghcr.io/${{ github.repository }}/samordning-hendelse-api:${{ inputs.version }}
          TEAM: pensjonsamhandling
      - name: Deploy krakenD config
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/apiendpoints/krakend-q2.yaml
      - name: Deploy apiEndpoints config
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/apiendpoints/apiendpoints-q2.yaml
