name: Deploy to production

env:
  "IMAGE_BASE": "docker.pkg.github.com/${{ github.repository }}/samordning-hendelse-api"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Which version to deploy (e.g. 2020.01.01-12.55-a1b2c3d4e5f6)"
        required: true

jobs:
  deploy_to_prod:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      # Deploy to prod-fss
      - name: Deploy to prod-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais.yaml
          IMAGE: "${{ env.IMAGE_BASE }}:${{ github.event.inputs.version }}"
          TEAM: pensjonsamhandling
          VARS: nais-prod-vars.yaml
