name: Test

on:
  push:
    branches:
      - '*'
      - '*/**'
      - '!release/*'
      - '!master'
  pull_request:

jobs:
  build_and_release:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Java 21'
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      # Build
      - name: Build & Test
        run: ./gradlew clean build --stacktrace
