name: Test

on:
  push:
    branches:
      - '*'
      - '*/**'
      - '!release/*'
      - '!master'
  pull_request:

jobs:
  build_and_release:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Java 21'
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      # Build
      - name: Build & Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean build --stacktrace

      - name: Publish Test Report
        uses: dorny/test-reporter@v3
        if: success() || failure() # Reports even if some tests fail
        with:
          name: Gradle Tests
          path: '**/build/test-results/**/*.xml' # Default Gradle test output path
          reporter: java-junit