name: Release to GitHub Package Registry

on:
  pull_request:

jobs:
  build_and_release:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'

      # Build
      - name: Build
        run: ./gradlew clean build
